### ISSUE TITLE
Logfile-Format

### ISSUE THREAD

**Issue by dg9vh** [BrandMeister/DMRHost#1]
Just a question for information purpose:

Is the logfile-format of this Client compatible to MMDVMHost? Cause of this question is: I was asked, if it would be possible to use my Dashboards for MMDVMHost with this Client without modification of the Dashboard...

Best 73
Kim
DG9VH

**Comment by zarya** [comment]
Should be no problem the code taking care of logging has not been changed.

**Comment by dg9vh** [comment]
mni thanks, Rudy told me same in telegram chat :-) so you can close this issue :-)
