### ISSUE TITLE
fatal error:

### ISSUE THREAD

**Issue by bf2spy** [BrandMeister/DMRHost#4]
UDPSocket.h:23:10: fatal error: netdb.h: No such file or directory

compile from windows with mingw and cmake

**Comment by stefansaraev** [comment]
it seems like you compile on an unsupported platform, or your buildsystem/headers are broken. 

on linux, netdb.h header comes with standard library (libc, musl). on ubuntu/debian make sure you have libc6-dev installed, on redhat / rpm based distros it is glibc-devel.

**Comment by bf2spy** [comment]
Yes, I failed on Windows, but successfully compiled it on Debian. Thank you.
